# ===========================
# PostgreSQL Configuration
# ===========================

# spring.datasource.url=jdbc\:postgresql://localhost:5432/ecommerce_db
# spring.datasource.username=postgres
# spring.datasource.password=YOUR_DB_PASSWORD
# spring.datasource.driver-class-name=org.postgresql.Driver


# ===========================
# JPA / Hibernate
# ===========================

# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.properties.hibernate.format_sql=true


# ===========================
# JWT Configuration
# ===========================

# jwt.secret=YOUR_JWT_SECRET
# jwt.expiration=900000
# jwt.refresh-expiration=604800000


# ===========================
# Spring AI / Groq
# ===========================

# spring.ai.openai.api-key=YOUR_API_KEY
# spring.ai.openai.base-url=https://api.groq.com/openai
# spring.ai.openai.chat.options.model=llama-3.1-8b-instant


# ===========================
# Server
# ===========================

# server.port=8080